-- Add a broader Instagram giveaway discovery pool from the July 2026 research
-- workbook. Existing/pruned sources are intentionally not re-enabled here.

insert into public.social_sources (platform, username, display_name, category, enabled)
values
  ('instagram', 'davelackiebeauty', 'Dave Lackie Beauty', 'beauty', true),
  ('instagram', 'foodnetwork', 'Food Network', 'food', true),
  ('instagram', 'hgtv', 'HGTV', 'home', true),
  ('instagram', 'omaze', 'Omaze', 'sweepstakes', true),
  ('instagram', 'prizeo', 'Charitybuzz Sweepstakes / Prizeo', 'sweepstakes', true),
  ('instagram', 'thefreebieguy', 'The Freebie Guy', 'giveaways', true),
  ('instagram', 'travelandleisure', 'Travel + Leisure', 'travel', true),
  ('instagram', 'thepointsguy', 'The Points Guy', 'travel', true),
  ('instagram', 'glowrecipe', 'Glow Recipe', 'beauty', true),
  ('instagram', 'scentbird', 'Scentbird', 'beauty', true),
  ('instagram', 'zevia', 'Zevia', 'food', true),
  ('instagram', 'drinkbubblr', 'BUBBL''R', 'food', true),
  ('instagram', 'colourpopcosmetics', 'ColourPop Cosmetics', 'beauty', true),
  ('instagram', 'elfcosmetics', 'e.l.f. Cosmetics', 'beauty', true),
  ('instagram', 'tartecosmetics', 'Tarte Cosmetics', 'beauty', true),
  ('instagram', 'benefitcosmetics', 'Benefit Cosmetics US', 'beauty', true),
  ('instagram', 'hudabeauty', 'Huda Beauty', 'beauty', true),
  ('instagram', 'toofaced', 'Too Faced Cosmetics', 'beauty', true),
  ('instagram', 'sephora', 'Sephora', 'beauty', true),
  ('instagram', 'ultabeauty', 'Ulta Beauty', 'beauty', true),
  ('instagram', 'nyxcosmetics', 'NYX Professional Makeup', 'beauty', true),
  ('instagram', 'sigmabeauty', 'Sigma Beauty', 'beauty', true),
  ('instagram', 'nordstrom', 'Nordstrom', 'retail', true),
  ('instagram', 'thedrybar', 'Drybar', 'beauty', true),
  ('instagram', 'royalcaribbean', 'Royal Caribbean', 'travel', true),
  ('instagram', 'lolablankets', 'Lola Blankets', 'home', true),
  ('instagram', 'keds', 'Keds', 'fashion', true),
  ('instagram', 'poshmark', 'Poshmark', 'fashion', true),
  ('instagram', 'maryruthorganics', 'MaryRuth''s', 'wellness', true),
  ('instagram', 'goodiegirlcookies', 'Goodie Girl', 'food', true),
  ('instagram', 'tootsieroll', 'Tootsie Roll Industries', 'food', true),
  ('instagram', 'simplemills', 'Simple Mills', 'food', true),
  ('instagram', 'madegoodfoods', 'MadeGood', 'food', true),
  ('instagram', 'honeystinger', 'Honey Stinger', 'food', true),
  ('instagram', 'jooliesdates', 'Joolies', 'food', true),
  ('instagram', 'doughlicious_dough', 'Doughlicious', 'food', true),
  ('instagram', 'naturesgardenus', 'Nature''s Garden', 'food', true),
  ('instagram', 'lumedeodorant', 'Lume Deodorant', 'personal_care', true),
  ('instagram', 'thirdlove', 'ThirdLove', 'fashion', true),
  ('instagram', 'pacificabeauty', 'Pacifica Beauty', 'beauty', true),
  ('instagram', 'laneige_us', 'LANEIGE US', 'beauty', true),
  ('instagram', 'vichyusa', 'Vichy USA', 'beauty', true),
  ('instagram', 'realcaboodles', 'Caboodles', 'beauty', true),
  ('instagram', 'piggypaint', 'Piggy Paint', 'beauty', true),
  ('instagram', 'babehair', 'Babe Hair', 'beauty', true),
  ('instagram', 'beyondyoga', 'Beyond Yoga', 'fashion', true),
  ('instagram', 'cliosnacks', 'Clio Snacks', 'food', true),
  ('instagram', 'crunchmastercrackers', 'Crunchmaster', 'food', true),
  ('instagram', 'dole', 'Dole', 'food', true),
  ('instagram', 'cocacola', 'Coca-Cola', 'food', true),
  ('instagram', 'goyafoods', 'Goya Foods', 'food', true),
  ('instagram', 'bordencheese', 'Borden Cheese', 'food', true),
  ('instagram', 'realgoodfoods', 'Real Good Foods', 'food', true),
  ('instagram', 'farmrichsnacks', 'Farm Rich', 'food', true),
  ('instagram', 'werthersoriginalus', 'Werther''s Original US', 'food', true),
  ('instagram', 'gladproducts', 'GLAD', 'home', true),
  ('instagram', 'armandhammer', 'ARM & HAMMER', 'consumer_goods', true),
  ('instagram', 'mybenebone', 'Benebone', 'pets', true),
  ('instagram', 'schleichofficial', 'Schleich', 'toys', true),
  ('instagram', 'penguinkids', 'Penguin Kids', 'books', true),
  ('instagram', 'bantambooks', 'Bantam Books', 'books', true),
  ('instagram', 'savorbeauty', 'Savor Beauty', 'beauty', true),
  ('instagram', 'javvycoffee', 'Javvy Coffee', 'food', true),
  ('instagram', 'novillahome', 'Novilla Home', 'home', true),
  ('instagram', 'purosoundlabs', 'Puro Sound Labs', 'tech', true),
  ('instagram', 'lactaid', 'LACTAID', 'food', true),
  ('instagram', 'behrpaint', 'BEHR Paint', 'home', true),
  ('instagram', 'kraususa', 'Kraus USA', 'home', true),
  ('instagram', '80acresfarms', '80 Acres Farms', 'food', true),
  ('instagram', 'honolulucookie', 'Honolulu Cookie Company', 'food', true),
  ('instagram', 'hailmerrysnacks', 'Hail Merry', 'food', true),
  ('instagram', 'wildechips', 'Wilde Chips', 'food', true),
  ('instagram', 'alvaradostreetbakery', 'Alvarado Street Bakery', 'food', true),
  ('instagram', 'goodnaturedbrand', 'Good Natured Brand', 'home', true),
  ('instagram', 'thegoldensecrets', 'The Golden Secrets', 'wellness', true),
  ('instagram', 'modlighting', 'MOD LIGHTING', 'home', true),
  ('instagram', 'fancypantsbaker', 'Fancypants Baking Co.', 'food', true),
  ('instagram', 'hightechtexan', 'High-Tech Texan', 'tech', true),
  ('instagram', 'gfuelenergy', 'G FUEL', 'gaming', true),
  ('instagram', 'newegg', 'Newegg', 'tech', true),
  ('instagram', 'bhphoto', 'B&H Photo Video', 'tech', true),
  ('instagram', 'gopro', 'GoPro', 'tech', true),
  ('instagram', 'sandalsresorts', 'Sandals Resorts', 'travel', true),
  ('instagram', 'beachesresorts', 'Beaches Resorts', 'travel', true),
  ('instagram', 'virginvoyages', 'Virgin Voyages', 'travel', true),
  ('instagram', 'expedia', 'Expedia', 'travel', true),
  ('instagram', 'cntraveler', 'Condé Nast Traveler', 'travel', true),
  ('instagram', 'lonelyplanet', 'Lonely Planet', 'travel', true),
  ('instagram', 'allure', 'Allure', 'beauty', true),
  ('instagram', 'goodhousekeeping', 'Good Housekeeping', 'lifestyle', true),
  ('instagram', 'delish', 'Delish', 'food', true),
  ('instagram', 'parishilton', 'Paris Hilton', 'celebrity', true)
on conflict (platform, username) do update
set
  display_name = excluded.display_name,
  category = excluded.category;
